jobs:
  workflow:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Start Up
        uses: actions/checkout@v2
      - name: Download Deps
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Check
        run: ./ci/check

name: Main

on:
  schedule:
    - cron: "5 2/3 * * *"
